"""Aliases and exclusions for source labels before PII normalization."""

from __future__ import annotations

LABEL_MAP = {
    "street_address": "<address>",
    "street": "<address>",
    "buildingnum": "<address>",
    "city": "<address>",
    "city_name": "<address>",
    "state": "<address>",
    "province": "<address>",
    "district": "<address>",
    "ward": "<address>",
    "country": "<address>",
    "postcode": "<address>",
    "zipcode": "<address>",
    "county": "<address>",
    "coordinate": "<address>",
    "address": "<address>",
    "location": "<address>",
    "addres": "<address>",
    "company_name": "<company_name>",
    "hospital": "<company_name>",
    "hotel_name": "<company_name>",
    "organization": "<company_name>",
    "clinic_name": "<company_name>",
    "organisation": "<company_name>",
    "bankname": "<company_name>",
    "hospitalname": "<company_name>",
    "company_nam": "<company_name>",
    "date": "<date>",
    "birthdate": "<date>",
    "time": "<date>",
    "date_time": "<date>",
    "date_of_birth": "<date>",
    "dob": "<date>",
    "dat": "<date>",
    "email": "<email_address>",
    "emailaddress": "<email_address>",
    "email_address": "<email_address>",
    "email_addres": "<email_address>",
    "first_name": "<human_name>",
    "givenname": "<human_name>",
    "last_name": "<human_name>",
    "surname": "<human_name>",
    "full_name": "<human_name>",
    "middle_name": "<human_name>",
    "user_name": "<human_name>",
    "human_name": "<human_name>",
    "patient_name": "<human_name>",
    "doctor_name": "<human_name>",
    "doctorname": "<human_name>",
    "username": "<human_name>",
    "name": "<human_name>",
    "human_nam": "<human_name>",
    "medical_record_number": "<id_number>",
    "employee_id": "<id_number>",
    "customer_id": "<id_number>",
    "national_id": "<id_number>",
    "idcardnum": "<id_number>",
    "certificate_license_number": "<id_number>",
    "health_plan_beneficiary_number": "<id_number>",
    "ssn": "<id_number>",
    "tax_id": "<id_number>",
    "taxnum": "<id_number>",
    "passport": "<id_number>",
    "passportnum": "<id_number>",
    "license_plate": "<id_number>",
    "pin": "<secret>",
    "password": "<secret>",
    "api_key": "<secret>",
    "access_token": "<secret>",
    "auth_token": "<secret>",
    "bearer_token": "<secret>",
    "csrf_token": "<secret>",
    "http_cookie": "<secret>",
    "session_cookie": "<secret>",
    "token": "<secret>",
    "credit_debit_card": "<id_number>",
    "creditcardnumber": "<id_number>",
    "credit_card_number": "<id_number>",
    "account_number": "<id_number>",
    "accountnum": "<id_number>",
    "policynum": "<id_number>",
    "bank_routing_number": "<id_number>",
    "swift_bic": "<id_number>",
    "swift_code": "<id_number>",
    "cvv": "<id_number>",
    "biometric_identifier": "<id_number>",
    "device_identifier": "<id_number>",
    "vehicle_identifier": "<id_number>",
    "unique_id": "<id_number>",
    "unique_identifier": "<id_number>",
    "ipv4": "<id_number>",
    "ipv6": "<id_number>",
    "mac_address": "<id_number>",
    "macaddress": "<id_number>",
    "id_number": "<id_number>",
    "driverlicensenum": "<id_number>",
    "socialnum": "<id_number>",
    "education_level": "<id_number>",
    "unit": "<id_number>",
    "serial_number": "<id_number>",
    "id_numbe": "<id_number>",
    "private_url": "<private_url>",
    "secret": "<secret>",
    "phone": "<phone_number>",
    "telephonenum": "<phone_number>",
    "fax_number": "<phone_number>",
    "mobile_number": "<phone_number>",
    "phone_number": "<phone_number>",
    "phone_numbe": "<phone_number>",
}

INVALID_LABELS = {
    "note",
    "compound",
    "medical_term",
    "label",
    "no_label",
    "comment",
    "think",
    "medication",
    "medication_name",
    "medication_instruction",
    "dosage",
    "diagnosis",
    "diagnosis_text",
    "procedure_description",
    "clinical_notes",
    "clinical_rm",
    "code",
    "device",
    "device_id",
    "department",
    "specialty",
    "administrative_note",
    "note_text",
    "description",
    "administrative_info",
    "medical_product",
    "lab_results",
    "clinical_information",
    "observation_value",
    "dosages",
    "amount",
    "procedure",
    "lab",
    "risk",
    "age",
    "status",
    "medical_unit",
    "field",
    "item",
    "section",
    "field_name",
    "url",
    "value",
    "key",
    "header",
    "title",
    "content",
    "text",
    "data",
    "info",
    "desc",
    "chest",
    "p",
    "div",
    "span",
    "br",
    "td",
    "tr",
    "th",
    "table",
    "Persetujuan_Tindakan_Medik",
    "COMMENT",
    "NOT_LABEL",
    "标签",
    "年龄",
    "性别",
    "TransmissionMethod",
    "relationship",
    "Specialization",
    "Medicine",
    "Indication",
    "RadiologistLicense",
    "fonction_signature",
    "Preleveur",
    "b",
    "Qualitaetsmanagement",
    "Reason",
    "Technique",
    "ContrastAgent",
    "metodePembayaranQRIS",
    "TandaTanganPenerima",
    "Hubungan",
    "UnitPoliklinik",
    "Relation",
    "Phonetic",
    "immediate",
    "underlying",
    "Kana",
    "Class",
    "Village",
    "District",
    "Province",
    "Nota",
    "NRNumber",
    "DigitalSignature",
    "KodProsedur",
    "DeskripsiProsedur",
    "especialidade",
    "setor_solicitante",
    "CRM",
    "TecnicoColeta",
    "медицина",
    "кодекс_лекарственного_средства",
    "Метка",
    "дата",
    "название_препарата",
    "CedulaProfesional",
    "Poliza",
    "Aseguradora",
    "FacilityName",
    "DepartmentName",
    "Department",
    "名称",
    "Address",
    "详细地址",
    "检验科",
    "心内科",
    "内分泌科",
    "华山医院",
    "协和医院",
    "上海市静安区南京西路1266号",
    "江苏省阳光市中山路188号",
    "上海市静安区南京西路街道弄堂18号乙单元301室",
    "北京市朝阳区建国路88号院SOHO现代城A座1205室",
    "Name",
    "Provider",
    "company",
    "Clinic",
    "Hospital",
    "Employer",
    "Insurance",
    "NomEtablissement",
    "NurseSignature",
    "a_pe",
    "khin_thit_thu",
    "tae_yin_phoo",
    "um_a_san",
}
